# config.yaml

# Input and Output Paths
input_file: "./sample.pdf"  # Path to input file (can be PDF, image, etc.)
output_dir: "./outputs"      # Path to save the output results

# Model Configuration (removed: generation is disabled)

# Parser Configuration
parser:
  pdf: true                               # Enable PDF parsing
  image: false                            # Enable image parsing
  text: true                              # Enable text parsing (if you need text files)

# Retrieval System Configuration
retrieval:
  method: "faiss"                         # Can be "faiss", "pinecone", "weaviate", etc.
  index_path: "/path/to/index"            # Path to document index for retrieval

# Logging Configuration
logging:
  enable_logging: true                    # Enable logging for the pipeline
  log_file: "pipeline.log"                # Log file name

# RAG Pipeline Configuration
rag:
  data_dir: "./data"          # Directory containing PDFs/images/txt to index
  index_path: "./rag_index.json"
  chunk_size: 500
  chunk_overlap: 50
  top_k: 3

# General Settings
general:
  batch_size: 5                           # Number of documents to process in parallel (if needed)
  retry_on_failure: true                  # Whether to retry if the pipeline fails at any stage
  max_retry_attempts: 3                   # Maximum retry attempts
